name: Build Docker image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-image:
    name: "ğŸ— Build Docker image"
    runs-on: ubuntu-latest
    outputs:
      api_image: ghcr.io/${{ github.repository }}:${{ github.sha }}
    steps:
      - name: "ğŸ“‚ Checkout"
        uses: actions/checkout@v3

      - name: "ğŸ”‘ Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: "ğŸ— Build image"
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          
