name: Build Docker image

on:
  push:
    branches:
      - master
  pull_request:

env:
  github_repository: ghcr.io/dispuuthamers/webapp

jobs:
  build-image:
    name: "ðŸ— Build Docker image"
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ“‚ Checkout"
        uses: actions/checkout@v3

      - name: "ðŸ”‘ Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - id: docker-build
        name: "ðŸ— Build image"
        run: |
          docker build -t ${{ env.github_repository }}:${{ github.sha }} .
          docker tag ${{ env.github_repository }}:${{ github.sha }} ${{ env.github_repository }}:latest
          docker push ${{ env.github_repository }}:${{ github.sha }}

      - name: "ðŸ“ Set output"
        run: |
          echo "Docker image" >> $GITHUB_STEP_SUMMARY
          echo "${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
